server:
  port: 7000
  
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    gateway:
       routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE 
            predicates: 
                  - Path=/users/**
            filters:
              - name: CircuitBreaker
                args:
                  name: USER-SERVICE 
                  fallbackuri: forword:/userServiceFallback
          - id: DEPARTMENT-SERVICE
            uri: lb://DEPARTMENT-SERVICE 
            predicates: 
                  - Path=/departments/**
            filters: 
              - name: CircuitBreaker
                args: 
                  name: DEPARTMENT-SERVICE 
                  fallbackuri: forword:/departmentServiceFallback


hystrix:  
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

management: 
  endpoints:
    web: 
      exposure:
        include: hystrix.stream



